const assert=require('node:assert/strict');
const G=require('../dist/engine.js');
const ids=s=>G.options(s).map(o=>o.id);
let s=G.create({origin:'merchant'});s.location='market';s.silver=100;
assert.ok(G.available(s).some(o=>o.id==='buymanual'));
s=G.step(s,'action:buymanual',()=>0);
assert.ok(!G.available(s).some(o=>o.id==='buymanual'));
const silver=s.silver;s=G.step(s,'action:buymanual',()=>0);assert.equal(s.silver,silver);
s.pending='mentor';assert.ok(ids(s).includes('serve'));assert.ok(ids(s).includes('guidance'));
s.flags.mentor=true;assert.ok(!ids(s).includes('serve'));assert.ok(ids(s).includes('guidance'));
s.manuals.push(2);assert.ok(!ids(s).includes('guidance'));assert.ok(ids(s).includes('depart'));
s.pending='spring';s.location='mountain';s.spring=1;
assert.ok(!ids(s).includes('common'));assert.ok(ids(s).includes('deep'));assert.ok(ids(s).includes('hidden'));
s.spring=2;assert.ok(!ids(s).includes('deep'));assert.ok(ids(s).includes('hidden'));
s.spring=3;assert.deepEqual(ids(s),['back']);s.pending=null;
assert.ok(!G.available(s).some(o=>o.id==='spring'));
s.location='market';s.elixirBoost=6;assert.ok(!G.available(s).some(o=>o.id==='buyelixir'));
s.elixirBoost=0;assert.ok(G.available(s).some(o=>o.id==='buyelixir'));
assert.ok(G.available(s).some(o=>o.id==='buygrain'));
console.log('Completed acquisition menus and repeatable supplies passed');
