const test=require('node:test'),assert=require('node:assert/strict'),G=require('../dist/engine.js');
const clone=s=>JSON.parse(JSON.stringify(s));
function entry(manual=3,wounds=0,defect=false){let s=G.create({name:'五气验收'});Object.assign(s,{stage:3,manual,manuals:[0,manual],decodedManuals:[0,manual],spring:4,month:100,ageMonths:292,grain:200,focus:100,wounds,totalProgress:400,pending:'attempt',foundationGrades:defect?[1,2,2]:[2,2,2],foundation:3,herbs:20,silver:30});s.progress=G.cap(s);s=G.step(s,'noop');s=G.step(s,'choice:steady',()=>0);s=G.step(s,'action:mingqiSense');s=G.step(s,'travel:mountain');s=G.step(s,'action:mingqiRidge');s=G.step(s,'travel:temple');s=G.step(s,'action:mingqiFriend');return s;}
const act=(s,id)=>G.step(s,`action:${id}`);
test('content limits and help requests describe actual benefits and weaknesses',()=>{let s=act(entry(),'qiAwaken');assert.ok(!G.available(s).some(o=>o.id==='qiAskAid'));assert.deepEqual(act(s,'qiAskAid'),s);s=stabilize(entry(4),'star').s;assert.match(G.fiveQiSummary(s).advice,/偏盛有出路/);assert.match(G.fiveQiSummary(s).advice,/测流/);assert.match(G.available(s).find(o=>o.id==='qiSeclude').detail,/暂不增长/);s.mingqi.fiveQi.values.wood=-2;const summary=G.fiveQiSummary(s);assert.match(summary.advice,/肝木耗损过深/);assert.doesNotMatch(summary.issues.join('；'),/脾土不足/);});
function stabilize(initial,method){let s=act(initial,'qiAwaken');const start=s.month,m=G.QI_METHODS[method];for(let i=0;i<m.months;i++){if(s.focus<m.focus)s=act(s,'mingqiRest');s=act(s,`qiLearn-${method}`);}if(s.focus<12)s=act(s,'mingqiRest');s=act(s,`qiCycle-${method}`);if(s.mingqi.fiveQi.blocked)s=act(s,'mingqiRest');return {s,months:s.month-start};}
test('three routes reach distinct nonuniform cycles with grade defects and wounds within the preset budget',()=>{const profiles={},rows=[];for(const [method,m] of Object.entries(G.QI_METHODS))for(const wounds of [0,3])for(const defect of [false,true]){const before=entry(m.manual,wounds,defect),{s,months}=stabilize(before,method);assert.ok(G.fiveQiSummary(s).stable,method);assert.ok(months<=12);assert.equal(s.ending,null);assert.deepEqual(s.affinityPoints,before.affinityPoints);assert.deepEqual(s.chapterCheckpoint,before.chapterCheckpoint);assert.deepEqual(s.npcFavor,before.npcFavor);assert.notEqual(new Set(Object.values(s.mingqi.fiveQi.values)).size,1);profiles[method]=s.mingqi.fiveQi.values;rows.push({method,wounds,defect,months,herbsSpent:before.herbs-s.herbs,focusNetChange:s.focus-before.focus,methodFocusCost:m.focus*m.months+12});let long=act(s,'mingqiRest');const longStart=long.month;for(let i=0;i<3;i++)long=act(long,'qiSeclude');assert.equal(long.month-longStart,36);assert.equal(long.mingqi.fiveQi.cultivationMonths,36);assert.ok(G.fiveQiSummary(long).stable);assert.equal(long.ending,null);}assert.notDeepEqual(profiles.taiwei,profiles.star);assert.notDeepEqual(profiles.star,profiles.green);require('node:fs').writeFileSync('tests/reports/five-qi-matrix.json',JSON.stringify({rulesVersion:G.RULE_VERSION,rows,stableMonths:36,recurrences:0,scope:'P0.4 + P0.6 circulation slice; no chaoyuan implemented'},null,2)+'\n');});
test('ordinary self cultivation requires no rare manual, aid or purchase',()=>{let s=entry(2);s=act(s,'qiAwaken');for(let i=0;i<6;i++){if(s.focus<8)s=act(s,'mingqiRest');s=act(s,'qiBreath');}assert.ok(G.fiveQiSummary(s).stable);assert.equal(s.mingqi.fiveQi.aid,null);assert.deepEqual(s.mingqi.fiveQi.items,{cooling:0,ward:0});});
test('arts consume time, a ward protects precisely earth, and repeated forceful casting disturbs circulation',()=>{let {s}=stabilize(entry(4),'star');for(let i=0;i<2;i++){if(s.focus<14)s=act(s,'mingqiRest');s=act(s,'qiLearnDrain');}s=G.step(s,'travel:market');s=act(s,'qiBuyWard');s=act(s,'mingqiRest');const month=s.month,earth=s.mingqi.fiveQi.values.earth;s=act(s,'qiDrain');assert.equal(s.month,month+1);assert.equal(s.mingqi.fiveQi.values.earth,earth);assert.equal(s.mingqi.fiveQi.items.ward,0);s=act(s,'mingqiRest');s=act(s,'qiDrain');assert.ok(!G.fiveQiSummary(s).stable);assert.match(G.fiveQiSummary(s).cause,/泄火/);s=act(s,'qiCycle-star');assert.ok(G.fiveQiSummary(s).stable);});
test('cooling medicine expires after three months and does not change real qi',()=>{let s=act(entry(),'qiAwaken');s=G.step(s,'travel:market');s=act(s,'qiBuyCooling');const values=clone(s.mingqi.fiveQi.values),month=s.month;s=act(s,'qiCooling');assert.equal(s.month,month);assert.deepEqual(s.mingqi.fiveQi.values,values);assert.ok(G.fiveQiSummary(s).temporary);assert.ok(!G.fiveQiSummary(s).stable);s=act(s,'qiMedicineRest');assert.equal(s.mingqi.fiveQi.cultivationMonths,1);for(let i=0;i<2;i++)s=act(s,'mingqiRest');assert.ok(!G.fiveQiSummary(s).temporary);assert.deepEqual(act(s,'qiMedicineRest'),s);assert.equal(s.mingqi.fiveQi.items.cooling,0);assert.deepEqual(act(s,'qiCooling'),s);});
test('aid clears only obstruction, records its witness and allows repayment',()=>{let s=act(entry(3,3),'qiAwaken');const values=clone(s.mingqi.fiveQi.values),wounds=s.wounds;s=act(s,'qiAskAid');assert.equal(s.mingqi.fiveQi.blocked,false);assert.deepEqual(s.mingqi.fiveQi.values,values);assert.equal(s.wounds,wounds);assert.ok(!G.fiveQiSummary(s).stable);assert.equal(s.mingqi.fiveQi.debt,1);assert.deepEqual(s.lifeHistory.find(e=>e.id==='mingqi.qiAid').knownBy,['cheng']);assert.deepEqual(act(s,'qiAskAid'),s);s=act(s,'qiRepay');assert.equal(s.mingqi.fiveQi.debt,0);assert.deepEqual(act(s,'qiRepay'),s);});
test('a private old rescue echoes only to its participant, never from personality or invented history',()=>{let s=entry();s.story.yeRoute='help';s.lifeTraits['重诺']=10;s=act(s,'qiAwaken');s=G.step(s,'travel:mountain');assert.deepEqual(act(s,'qiYeEcho'),s);G.remember(s,'choice.herbalist.help.25',{actors:[],choice:'help',text:'旧日分药'});s.lifeHistory.at(-1).chapter='opening';const before=clone(s);s=act(s,'qiYeEcho');assert.equal(s.herbs,before.herbs+1);assert.equal(s.mingqi.fiveQi.items.cooling,1);assert.deepEqual(s.lifeHistory.find(e=>e.id==='mingqi.qiYeEcho').knownBy,['ye']);assert.deepEqual(s.npcFavor,before.npcFavor);assert.deepEqual(act(s,'qiYeEcho'),s);});
test('new state reloads deterministically, old checkpoints restore exactly and illegal commands do nothing',()=>{const initial=entry(),{s}=stabilize(initial,'green'); // green not owned: command must be ignored
 assert.equal(s.mingqi.fiveQi.method,null);assert.deepEqual(act(s,'qiCycle-invalid'),s);const normalized=G.migrate(clone(s));assert.deepEqual(G.migrate(clone(normalized)),normalized);assert.deepEqual(normalized.mingqi,s.mingqi);const star=stabilize(entry(4),'star').s;assert.deepEqual(G.migrate(clone(star)).mingqi,star.mingqi);const old=clone(initial);assert.equal(old.mingqi.fiveQi,undefined);assert.deepEqual(G.migrate(clone(old)).mingqi,old.mingqi);const dead=clone(star);dead.ending={kind:'death'};const restored=G.step(dead,'checkpoint:opening');assert.equal(restored.mingqi.fiveQi,undefined);assert.deepEqual(restored.chapterCheckpoint,star.chapterCheckpoint);const early=G.create();assert.deepEqual(act(early,'qiAwaken'),early);let hungry=clone(star);hungry.grain=11;assert.deepEqual(act(hungry,'qiSeclude'),hungry);});
