const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),G=require('../dist/engine.js');
const clone=x=>JSON.parse(JSON.stringify(x));
function state(){let s=G.create({name:'观息客'});Object.assign(s,{stage:3,month:80,ageMonths:272,manual:3,manuals:[0,3],spring:4,progress:200,totalProgress:400,foundation:3,foundationGrades:[2,2,2],focus:100,grain:30,pending:'attempt'});return G.step(s,'choice:steady',()=>0);}
function mount(initial,narrow=false,store=new Map()){
 if(initial)store.set(G.KEY,JSON.stringify(initial));const ids=new Set([...fs.readFileSync('dist/index.html','utf8').matchAll(/\bid="([^"]+)"/g)].map(m=>m[1])),elements=new Map(),handlers=new Map();
 function element(id){assert.ok(ids.has(id),`missing DOM ${id}`);if(!elements.has(id))elements.set(id,{id,hidden:false,innerHTML:'',textContent:'',style:{},dataset:{},classList:{toggle(){}},setAttribute(){},addEventListener(t,f){handlers.set(`${id}:${t}`,f);},querySelectorAll(){return [];},closest(){return {classList:{toggle(){}}};},focus(){},scrollIntoView(){},getBoundingClientRect(){return {top:300};},getClientRects(){return [1];},showModal(){this.shown=true;}});return elements.get(id);}
 const document={getElementById:element,querySelectorAll(){return [];},addEventListener(t,f){handlers.set(`document:${t}`,f);}};
 const context={window:{LingxiEngine:G,matchMedia(){return {matches:narrow};},scrollTo(){},scrollBy(){}},document,localStorage:{getItem(k){return store.get(k)||null;},setItem(k,v){store.set(k,v);},removeItem(k){store.delete(k);}},requestAnimationFrame(f){f();},console};
 vm.runInNewContext(fs.readFileSync('dist/app.js','utf8'),context);
 function click(command){const b={dataset:{command},disabled:false,textContent:command,getBoundingClientRect(){return {top:300};}};handlers.get('document:click')({target:{closest(){return b;}}});}
 return {element,store,handlers,click,current:()=>JSON.parse(store.get(G.KEY))};
}
test('travel and exploration objectives are exposed on desktop and narrow screens',()=>{for(const narrow of [false,true]){const H=require('./chapter-two-helpers.cjs');const s=H.stable(H.entry(),'taiwei'),ui=mount(s,narrow);assert.match(ui.element('mobile-travel-list').innerHTML,/河灯市.*两月/);assert.match(ui.element('chapter-intro').innerHTML,/赤炉测流/);ui.click('travel:redValley');assert.equal(ui.current().location,'redValley');assert.match(ui.element('mobile-action-list').innerHTML,/金水导流/);ui.click('action:expFlow');assert.match(ui.element('chapter-intro').innerHTML,/测流 1\/3/);assert.doesNotMatch(ui.element('chapter-intro').innerHTML,/成环即到本版内容终点/);}});
test('desktop and mobile entry show chapter two, milestones and lifespan without invalid progress',()=>{for(const narrow of [false,true]){const ui=mount(state(),narrow);assert.equal(ui.element('chapter-brand').textContent,'明气初行 · 求道第二章');assert.equal(ui.element('stage').textContent,'明气');assert.match(ui.element('chapter-deadline').textContent,/已过仙凡/);assert.match(ui.element('compact-deadline').textContent,/余寿/);assert.equal(ui.element('progress').textContent,'0 / 3 项');assert.equal(ui.element('progress-bar').style.width,'0%');assert.equal(ui.element('chapter-intro').hidden,false);assert.doesNotMatch([...ui.element('arts-content').innerHTML,ui.element('profile-content').innerHTML,ui.element('chapter-intro').innerHTML].join(''),/NaN|undefined/);ui.click('action:mingqiSense');assert.equal(ui.current().mingqi.completed.length,1);assert.match(ui.element('arts-content').innerHTML,/观息术 · 初学/);assert.equal(ui.element('progress').textContent,'1 / 3 项');}});
test('ordinary saves preserve a separate opening checkpoint and confirmed death rollback works in the UI',()=>{const s=state(),ui=mount(s),cp=ui.store.get(G.CHECKPOINT_KEY);assert.ok(cp);ui.click('action:mingqiSense');assert.equal(ui.store.get(G.CHECKPOINT_KEY),cp);const broken=ui.current();delete broken.chapterCheckpoint;const reload=mount(broken,false,ui.store);assert.ok(reload.current().chapterCheckpoint);let dead=clone(reload.current());dead.ending={kind:'death',body:'测试身死',grade:''};const terminal=mount(dead,false,ui.store);assert.match(terminal.element('ending').innerHTML,/从开脉之时重来/);terminal.handlers.get('document:click')({target:{id:'checkpoint-restore',closest(){return null;}}});assert.equal(terminal.element('checkpoint-dialog').shown,true);terminal.element('checkpoint-dialog').returnValue='confirm';terminal.handlers.get('checkpoint-dialog:close')();assert.deepEqual(terminal.current(),s);assert.equal(terminal.store.get(G.CHECKPOINT_KEY),cp);assert.equal(terminal.element('ending').hidden,true);});
test('desktop and narrow screens expose actual five qi, method choices and persisted circulation',()=>{for(const narrow of [false,true]){let s=state();s=G.step(s,'action:mingqiSense');s=G.step(s,'travel:mountain');s=G.step(s,'action:mingqiRidge');s=G.step(s,'travel:temple');s=G.step(s,'action:mingqiFriend');s.grain=100;s.focus=100;s.decodedManuals=[0,3];const ui=mount(s,narrow),checkpoint=ui.store.get(G.CHECKPOINT_KEY);assert.match(ui.element('mobile-action-list').innerHTML,/qiAwaken/);ui.click('action:qiAwaken');assert.match(ui.element('chapter-intro').innerHTML,/心火 · 偏盛/);assert.match(ui.element('chapter-intro').innerHTML,/肾水 · 偏衰/);assert.match(ui.element('mobile-action-list').innerHTML,/qiLearn-taiwei/);for(let i=0;i<3;i++)ui.click('action:qiLearn-taiwei');ui.click('action:qiCycle-taiwei');assert.match(ui.element('chapter-intro').innerHTML,/循环自持/);assert.match(ui.element('chapter-intro').innerHTML,/太微 · 金水制火/);assert.match(ui.element('mobile-action-list').innerHTML,/qiSeclude/);assert.equal(ui.store.get(G.CHECKPOINT_KEY),checkpoint);const reload=mount(ui.current(),narrow,ui.store);assert.match(reload.element('chapter-intro').innerHTML,/循环自持/);assert.doesNotMatch([reload.element('chapter-intro').innerHTML,reload.element('arts-content').innerHTML].join(''),/NaN|undefined/);}});
