const assert=require('node:assert/strict'),test=require('node:test'),G=require('../dist/engine.js');
const clone=x=>JSON.parse(JSON.stringify(x));
function ready(origin='scholar',talent='clarity',manual=3){const s=G.create({name:'明气验收',origin,talent});Object.assign(s,{stage:3,manual,manuals:[0,manual],decodedManuals:[0,manual],spring:4,month:100,ageMonths:292,grain:30,focus:100,wounds:0,totalProgress:400,pending:'attempt',foundationGrades:[2,2,2],foundation:3});s.progress=G.cap(s);G.remember(s,'oldPromise',{actors:['cheng'],tags:['履约'],outcome:'kept',text:'曾守卷。'});G.markTrait(s,'重诺',2);return G.step(s,'noop');}
const enter=(s=ready())=>G.step(s,'choice:steady',()=>0);
function finish(s){s=G.step(s,'action:mingqiSense');s=G.step(s,'travel:mountain');s=G.step(s,'action:mingqiRidge');s=G.step(s,'travel:temple');return G.step(s,'action:mingqiFriend');}
test('opening immediately enters mingqi, preserving all inherited state in an immutable checkpoint',()=>{const before=ready(),s=enter(before);assert.equal(s.chapter,'mingqi');assert.equal(s.stage,4);assert.equal(s.version,12);assert.equal(s.ending,null);assert.equal(s.lifeLimitMonths,before.lifeLimitMonths+360);assert.equal(s.month,101);assert.ok(s.openingResult.grade);assert.equal(s.chapterCheckpoint.version,1);assert.equal(s.chapterCheckpoint.state.chapterCheckpoint,undefined);const n=clone(s);delete n.chapterCheckpoint;assert.deepEqual(s.chapterCheckpoint.state,n);for(const k of ['origin','talent','manuals','practice','foundationGrades','spring','npcFavor','lifeTraits'])assert.deepEqual(s[k],before[k],k);assert.ok(G.hasMemory(s,'oldPromise'));assert.ok(G.hasMemory(s,'realm.mingqi'));assert.ok(G.memoriesByTag(s,'attempt').length);assert.equal(before.chapter,'opening');});
test('27 origin/talent/manual combinations finish the safe introduction in three months without grinding',()=>{let count=0;for(const origin of Object.keys(G.ORIGINS))for(const talent of Object.keys(G.TALENTS))for(const manual of [3,4,5]){const s=enter(ready(origin,talent,manual)),n=finish(s);count++;assert.equal(n.month-s.month,3);assert.equal(n.ending,null);assert.equal(n.mingqi.introComplete,true);assert.equal(n.mingqi.completed.length,3);assert.ok(n.mingqi.arts.includes('observeBreath'));for(const k of ['totalProgress','affinityPoints','root','wit','body','dao','social','lifeLimitMonths','npcFavor','chapterCheckpoint'])assert.deepEqual(n[k],s[k],k);assert.deepEqual(G.step(G.step(n,'action:mingqiRidge'),'action:mingqiFriend'),n);}assert.equal(count,27);});
test('low/high opening grades and inherited wounds all have a viable introduction',()=>{for(const grade of ['下下品','中中品','上上品'])for(const wounds of [0,1,3]){const old=ready();old.version=11;old.pending=null;old.wounds=wounds;old.ending={kind:'success',grade,body:'旧结局'};old.lifeLimitMonths+=360;const n=finish(G.migrate(clone(old)));assert.equal(n.mingqi.introComplete,true);assert.equal(n.openingResult.grade,grade);assert.equal(n.wounds,wounds);assert.equal(n.lifeLimitMonths,old.lifeLimitMonths);}});
test('reload and migration are idempotent and never add a second lifespan reward',()=>{const old=ready();old.version=11;old.pending=null;old.ending={kind:'success',grade:'中下品',body:'旧结局'};old.lifeLimitMonths+=360;const s=G.migrate(clone(old));assert.deepEqual(G.migrate(clone(s)),s);assert.equal(s.lifeLimitMonths,old.lifeLimitMonths);const n=finish(s);assert.deepEqual(G.migrate(clone(n)),n);for(const version of [2,3,4,5,6,7,8,9,10,11]){const first=G.create();first.version=version;const moved=G.migrate(clone(first));assert.equal(moved.version,12);assert.equal(moved.chapter,'opening');assert.equal(moved.chapterCheckpoint,undefined);}});
test('death/lifespan rollback restores the exact snapshot and living/mortal characters cannot rewind',()=>{const s=enter(),expected=clone(s);let dead=finish(s);dead.wounds=6;dead.location='mountain';dead=G.step(dead,'action:mingqiForage');assert.equal(dead.ending.kind,'death');assert.deepEqual(G.step(G.migrate(clone(dead)),'checkpoint:opening'),expected);assert.deepEqual(G.step(s,'checkpoint:opening'),s);let expired=finish(s);expired.lifeLimitMonths=expired.ageMonths+1;expired=G.step(expired,'action:mingqiRest');assert.equal(expired.ending.kind,'lifespan');assert.deepEqual(G.step(expired,'checkpoint:opening'),expected);const first=ready();first.ending={kind:'mortal'};assert.deepEqual(G.step(first,'checkpoint:opening'),first);});
test('same preparation has a stable seed across reload and rollback without consuming injected RNG',()=>{const s=enter(),prep={manual:s.manual,herbs:s.herbs,wounds:s.wounds},roll=G.chapterRoll(s,'future朝元',prep);assert.equal(roll,G.chapterRoll(G.migrate(clone(s)),'future朝元',prep));let dead=finish(s);dead.wounds=6;dead.location='mountain';dead=G.step(dead,'action:mingqiForage');let calls=0;const back=G.step(dead,'checkpoint:opening',()=>{calls++;return .9;});assert.equal(calls,0);assert.equal(roll,G.chapterRoll(back,'future朝元',prep));assert.notEqual(roll,G.chapterRoll(back,'future朝元',{...prep,herbs:prep.herbs+1}));});
test('turning thirty is allowed in mingqi while the first-chapter deadline remains enforced',()=>{let s=enter();s.ageMonths=359;s.lifeLimitMonths=900;s=G.step(s,'action:mingqiRest');assert.equal(s.ageMonths,360);assert.equal(s.ending,null);let first=G.create();first.ageMonths=359;first.grain=30;first=G.step(first,'action:rest');assert.equal(first.ending.kind,'retired');});
test('utility art and resupply are reachable without reopening first-chapter reward loops',()=>{let s=enter();s=G.step(s,'action:mingqiSense');s=G.step(s,'action:mingqiObserve');assert.deepEqual(G.step(s,'action:mingqiObserve'),s);for(const id of ['cultivate','attempt','stage','manual','spar-novice','secludeYear'])assert.deepEqual(G.step(s,`action:${id}`),s,id);let hungry=clone(s);Object.assign(hungry,{focus:0,grain:0,silver:0,location:'mountain'});assert.ok(G.available(hungry).some(x=>!x.disabled));hungry=G.step(hungry,'action:mingqiRest');hungry=G.step(hungry,'action:mingqiForage');assert.ok(hungry.grain>0);assert.equal(hungry.ending,null);const herbs=hungry.herbs;hungry=G.step(hungry,'action:mingqiRidge');assert.equal(hungry.herbs,herbs+2);assert.deepEqual(G.step(hungry,'action:mingqiRidge'),hungry);});
test('an annual volume continues after the partial opening chapter closing volume',()=>{let s=enter();const yr=G.year(s.month);assert.equal(s.books.find(x=>x.year===yr).partial,true);s=finish(s);while(s.month%12!==0)s=G.step(s,'action:mingqiRest');assert.equal(s.books.find(x=>x.year===yr).partial,false);assert.ok(s.books.find(x=>x.year===yr).lines.some(x=>x.includes('观息')));});
